name: Deploy nodejs main branch

on: 
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: DEPLOY
        uses: favware/ssh-remote-action@v1
        with:
          host: ${{ secrets.NODEJS_SERVER_HOST }}
          username: ${{ secrets.NODEJS_SERVER_USER }}
          key: ${{ secrets.NODEJS_SERVER_KEY }} 
          command:
            cd /nodejs/AI_chat_supporter_react_nodejs &&
            git pull origin main &&
            npm install &&
            pm2 restart nodeapp/src/server.js
